version: '3.0'

services:

  postgres:
    image: postgres:13-alpine
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - ./postgresql/dumps:/code/dumps
      - ./postgresql/data:/var/lib/postgresql/data

