# Generated by Django 5.1 on 2024-08-27 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinate_x', models.FloatField(verbose_name='Координата X')),
                ('coordinate_y', models.FloatField(verbose_name='Координата Y')),
                ('height', models.FloatField(default=200, verbose_name='Высота')),
                ('width', models.FloatField(default=300, verbose_name='Ширина')),
            ],
            options={
                'verbose_name': 'Блок',
                'verbose_name_plural': 'Блоки',
            },
        ),
        migrations.CreateModel(
            name='Arrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrow_from', to='elements.block', verbose_name='Откуда')),
                ('block_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrow_to', to='elements.block', verbose_name='Куда')),
            ],
            options={
                'verbose_name': 'Стрелка',
                'verbose_name_plural': 'Стрелки',
            },
        ),
    ]
